### ISSUE TITLE
jte-kotlin is incompatible with Kotlin 2.1.0

### ISSUE THREAD

**Issue by GregoryBevan** [casid/jte#409]
Hello,

I am using JTE and JTE-Kotlin in one of my projects. After upgrading the Kotlin version to 2.1.0, I noticed that the tests for template generation no longer pass, and I encounter the following error.

```shell
java.lang.NoSuchMethodError: 'org.jetbrains.kotlin.cli.common.ExitCode org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.exec(org.jetbrains.kotlin.cli.common.messages.MessageCollector, org.jetbrains.kotlin.config.Services, org.jetbrains.kotlin.cli.common.arguments.CommonToolArguments)'

	at gg.jte.compiler.kotlin.KotlinClassCompiler.compile(KotlinClassCompiler.java:42)
	at gg.jte.compiler.TemplateCompiler.precompileClasses(TemplateCompiler.java:114)
	at gg.jte.compiler.TemplateCompiler.precompile(TemplateCompiler.java:94)
	at gg.jte.compiler.TemplateCompiler.load(TemplateCompiler.java:50)
	at gg.jte.TemplateEngine.lambda$resolveTemplateOnDemand$0(TemplateEngine.java:354)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
	at gg.jte.TemplateEngine.resolveTemplateOnDemand(TemplateEngine.java:347)
	at gg.jte.TemplateEngine.resolveTemplate(TemplateEngine.java:337)
	at gg.jte.TemplateEngine.render(TemplateEngine.java:228)
	at testjte.JteTest.should render template(JteTest.kt:18)
```

The error is related to the `kotlin-compiler-embeddable` library.

I have isolated this issue in a sample project, which is available [here](https://github.com/GregoryBevan/test-jte). 

I also tried debugging in IntelliJ, and if I set breqakpoint on line 42 of  the `KotlinClassCompiler` class and  manually call the `exec` method, it works—as if the classpath is different during the actual execution.

Additionally, I checked out JTE repository, and attempted the upgrade of Kotlin version directly in jte-kotin module. The tests fails with the same error.

**Comment by GregoryBevan** [comment]
I have discovered the cause of the issue. It turns out that I need to upgrade the JDK to version 21 to resolve it.

**Comment by GregoryBevan** [comment]
I have discovered the cause of the issue. It turns out that I need to upgrade the JDK to version 21 to resolve it.
